plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'com.example.activity'
    compileSdk 35

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId 'com.example.activity'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    sourceSets {
        main {
            python.srcDirs = [
                "src/main/python"
            ]
        }
    }

    signingConfigs {
        release {
            storeFile file('../../Meetings_apk/meetings-release.jks')
            storePassword 'Alicja@@13!!!'
            keyAlias 'meetings'
            keyPassword 'Alicja@@13!!!'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

def activityApiDir = file("../../activity_api")
def apkPythonDir = file("src/main/python")

tasks.register("copyActivityApiPython") {
    inputs.files(
        fileTree(activityApiDir) {
            include "main.py"
            include "db.py"
            include "enums.py"
            include "templates.py"
            include "validators.py"
            include "activity.db"
            include "routers/**"
            include "templates/**"

            exclude "**/__pycache__/**"
            exclude "**/*.pyc"
        }
    )

    outputs.dir(apkPythonDir)

    doLast {
        println "========================================"
        println "KOPIOWANIE activity_api -> APK Python"
        println "Źródło:  ${activityApiDir}"
        println "Cel:     ${apkPythonDir}"
        println "========================================"

        copy {
            from activityApiDir
            into apkPythonDir

            include "main.py"
            include "db.py"
            include "enums.py"
            include "templates.py"
            include "validators.py"
            include "activity.db"
            include "routers/**"
            include "templates/**"

            exclude "**/__pycache__/**"
            exclude "**/*.pyc"
        }
    }
}

tasks.configureEach {
    if (name == "mergeDebugPythonSources" ||
        name == "mergeReleasePythonSources") {

        dependsOn("copyActivityApiPython")
    }
}

chaquopy {
    defaultConfig {
        version = "3.12"

        pip {
            install "fastapi==0.109.2"
            install "uvicorn==0.42.0"
            install "jinja2==3.1.6"
            install "python-multipart==0.0.32"
        }
    }
}
